CREATE TABLE dimTime(
    time_key int PRIMARY KEY NOT NULL,
    FullDateAlternateKey DATE,
    PersianFullDateAlternateKey DATE,
    DayNumberOfWeek TINYINT,
    PersianDayNumberOfWeek TINYINT,
    EnglishDayNameOfWeek VARCHAR(10),
    PersianDayNameOfWeek NVARCHAR(10),
    DayNumberOfMonth TINYINT,
    PersianDayNumberOfMonth TINYINT,
    DayNumberOfYear SMALLINT,
    PersianDayNumberOfYear SMALLINT,
    WeekNumberOfYear TINYINT,
    PersianWeekNumberOfYear TINYINT,
    EnglishMonthName VARCHAR(10),
    PersianMonthName NVARCHAR(10),
    MonthNumberOfYear TINYINT,
    PersianMonthNumberOfYear TINYINT,
    CalendarQuarter TINYINT,
    PersianCalendarQuarter TINYINT,
    CalendarYear int,
    PersianCalendarYear int,
    CalendarSemester TINYINT,
    PersianCalendarSemester TINYINT,
);